import { createClient } from "@supabase/supabase-js";
import { NextResponse } from "next/server";

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

const supabase = createClient(supabaseUrl, supabaseServiceKey);

// Sample high-quality lobby/interior images for UAE luxury theme
const SAMPLE_IMAGES = [
  {
    image_url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
    title: "Grand Lobby Entrance",
    description: "Elegant marble flooring with contemporary design",
    category: "lobby",
    order_index: 1
  },
  {
    image_url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80",
    title: "Premium Reception Area",
    description: "Sophisticated welcome area with gold accents",
    category: "reception",
    order_index: 2
  },
  {
    image_url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
    title: "Executive Office Suite",
    description: "Modern workspace with panoramic city views",
    category: "office",
    order_index: 3
  },
  {
    image_url: "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&q=80",
    title: "Luxury Meeting Room",
    description: "State-of-the-art meeting facilities",
    category: "meeting",
    order_index: 4
  },
  {
    image_url: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&q=80",
    title: "VIP Customer Lounge",
    description: "Exclusive waiting area with premium amenities",
    category: "lounge",
    order_index: 5
  },
  {
    image_url: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80",
    title: "Corporate Atrium",
    description: "Stunning architectural centerpiece",
    category: "atrium",
    order_index: 6
  },
  {
    image_url: "https://images.unsplash.com/photo-1600573472591-ee6981cf35de?w=800&q=80",
    title: "Business Center",
    description: "Full-service business facilities",
    category: "business",
    order_index: 7
  },
  {
    image_url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&q=80",
    title: "Conference Hall",
    description: "Large-scale event venue",
    category: "conference",
    order_index: 8
  },
  {
    image_url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&q=80",
    title: "Reception Desk",
    description: "Professional front desk service",
    category: "reception",
    order_index: 9
  },
  {
    image_url: "https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800&q=80",
    title: "Executive Suite",
    description: "Premium private office space",
    category: "office",
    order_index: 10
  },
  {
    image_url: "https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?w=800&q=80",
    title: "Modern Interior",
    description: "Contemporary design excellence",
    category: "interior",
    order_index: 11
  },
  {
    image_url: "https://images.unsplash.com/photo-1600607688066-890987f18a86?w=800&q=80",
    title: "Corporate Interior",
    description: "Professional environment",
    category: "interior",
    order_index: 12
  }
];

export async function POST(request) {
  try {
    // Verify admin secret
    const body = await request.json();
    const { secret } = body;
    
    if (secret !== "riadh-admin-secret-2024") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Check if gallery already has data
    const { data: existingData, error: checkError } = await supabase
      .from("gallery")
      .select("id")
      .limit(1);
    
    if (checkError) {
      // Table might not exist, return instructions
      return NextResponse.json({ 
        error: "Gallery table does not exist",
        instructions: "Please create the gallery table in Supabase with the following SQL:\n\nCREATE TABLE gallery (\n  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n  image_url TEXT NOT NULL,\n  title TEXT,\n  description TEXT,\n  category TEXT DEFAULT 'general',\n  order_index INTEGER DEFAULT 0,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP\n);"
      }, { status: 500 });
    }
    
    if (existingData && existingData.length > 0) {
      return NextResponse.json({ 
        message: "Gallery already initialized",
        count: existingData.length
      });
    }
    
    // Insert sample images
    const { data, error } = await supabase
      .from("gallery")
      .insert(SAMPLE_IMAGES)
      .select();
    
    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }
    
    return NextResponse.json({ 
      success: true, 
      message: `Successfully added ${data.length} sample images to gallery` 
    });
    
  } catch (error) {
    return NextResponse.json({ error: "Failed to initialize gallery" }, { status: 500 });
  }
}
